//! Thin HTTP client over the daemon's local API (SPEC.md §15/§16).
//!
//! The CLI NEVER touches the database: every command speaks to the daemon
//! (or, for `init`/`doctor`, only reads local environment state). The client
//! mirrors the daemon's address/token resolution so a token generated by
//! `kern init` is picked up automatically:
//!
//! - address: `KERN_API_ADDR` or `127.0.0.1:8787`
//! - token:   `KERN_TOKEN` wins, else `$KERN_HOME/token` (when present)
//!
//! Errors carry the daemon's §13 shape `{code, message, detail?}`; the
//! `Display` impl prints a compact, actionable line for the terminal.

use std::path::Path;
use std::time::Duration;

use reqwest::StatusCode;
use serde::Deserialize;
use serde_json::Value;

/// Default API bind address (SPEC.md §17).
pub const DEFAULT_API_ADDR: &str = "127.0.0.1:8787";

/// A structured API error (`SPEC.md §13`) or a transport failure.
#[derive(Debug)]
pub enum ClientError {
    /// The daemon answered with a structured `{code, message, detail?}` body.
    Api {
        status: StatusCode,
        code: String,
        message: String,
        detail: Option<Value>,
    },
    /// Connection-level failure: the daemon is not reachable.
    Unreachable(String),
    /// Any other transport/decoding failure.
    Transport(String),
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ClientError::Api {
                status,
                code,
                message,
                detail,
            } => {
                write!(f, "{code}: {message} (HTTP {})", status.as_u16())?;
                if let Some(detail) = detail {
                    write!(f, " — {detail}")?;
                }
                Ok(())
            }
            ClientError::Unreachable(addr) => write!(
                f,
                // `addr` is the full base URL (scheme included), not a bare host:port.
                "cannot reach the Kern daemon at {addr} — is `kern daemon` running? \
                 (start it in a terminal with `kern daemon`)"
            ),
            ClientError::Transport(msg) => f.write_str(msg),
        }
    }
}

impl std::error::Error for ClientError {}

/// The §13 error envelope, parsed out of a non-2xx JSON response.
#[derive(Debug, Deserialize)]
struct ApiErrorBody {
    code: String,
    message: String,
    #[serde(default)]
    detail: Option<Value>,
}

/// The daemon HTTP client.
#[derive(Clone)]
pub struct Client {
    http: reqwest::Client,
    base: String,
    token: Option<String>,
}

impl Client {
    /// Build a client from the environment (address + token resolution).
    pub fn from_env() -> Result<Self, ClientError> {
        let addr = std::env::var("KERN_API_ADDR").unwrap_or_else(|_| DEFAULT_API_ADDR.to_string());
        Self::new(&addr, load_token(&default_home()))
    }

    pub fn new(addr: &str, token: Option<String>) -> Result<Self, ClientError> {
        let base = if addr.contains("://") {
            addr.trim_end_matches('/').to_string()
        } else {
            format!("http://{addr}")
        };
        Ok(Self {
            http: reqwest::Client::builder()
                .connect_timeout(Duration::from_secs(2))
                .timeout(Duration::from_secs(30))
                .build()
                .map_err(|e| ClientError::Transport(format!("build http client: {e}")))?,
            base,
            token,
        })
    }

    /// The resolved base URL (for `kern version` output).
    pub fn base_url(&self) -> &str {
        &self.base
    }

    fn authed(&self, req: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        match &self.token {
            Some(token) => req.bearer_auth(token),
            None => req,
        }
    }

    async fn send(&self, req: reqwest::RequestBuilder) -> Result<reqwest::Response, ClientError> {
        let response = req.send().await.map_err(|e| {
            if e.is_connect() || e.is_timeout() {
                ClientError::Unreachable(self.base.clone())
            } else {
                ClientError::Transport(format!("request failed: {e}"))
            }
        })?;
        Ok(response)
    }

    async fn json_response(&self, req: reqwest::RequestBuilder) -> Result<Value, ClientError> {
        let response = self.send(req).await?;
        let status = response.status();
        if !status.is_success() {
            return Err(self.error_from(status, response).await);
        }
        response
            .json::<Value>()
            .await
            .map_err(|e| ClientError::Transport(format!("decode response: {e}")))
    }

    async fn error_from(&self, status: StatusCode, response: reqwest::Response) -> ClientError {
        match response.json::<ApiErrorBody>().await {
            Ok(body) => ClientError::Api {
                status,
                code: body.code,
                message: body.message,
                detail: body.detail,
            },
            Err(_) => ClientError::Api {
                status,
                code: "HTTP_ERROR".into(),
                message: format!("the daemon returned HTTP {}", status.as_u16()),
                detail: None,
            },
        }
    }

    // ------------------------------------------------------------------
    // Endpoints
    // ------------------------------------------------------------------

    /// `GET /health`
    pub async fn health(&self) -> Result<Value, ClientError> {
        self.json_response(self.authed(self.http.get(format!("{}/health", self.base))))
            .await
    }

    /// `GET /agents`
    pub async fn list_agents(&self) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(self.authed(self.http.get(format!("{}/agents", self.base))))
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode agents: {e}")))
    }

    /// `POST /agents` with a validated spec (the daemon re-validates).
    pub async fn create_agent(&self, spec: &Value) -> Result<Value, ClientError> {
        self.json_response(
            self.authed(
                self.http
                    .post(format!("{}/agents", self.base))
                    .json(&serde_json::json!({ "spec": spec })),
            ),
        )
        .await
    }

    /// `GET /agents/{id}` — the §4.1 wire view.
    pub async fn get_agent(&self, id: &str) -> Result<Value, ClientError> {
        self.json_response(self.authed(self.http.get(format!("{}/agents/{id}", self.base))))
            .await
    }

    /// `POST /agents/{id}/{action}` for start|pause|resume|checkpoint|terminate.
    ///
    /// Some lifecycle actions (pause/resume/terminate) answer 202 with an
    /// EMPTY body; others (start/checkpoint) answer JSON. Accept both.
    pub async fn lifecycle(&self, id: &str, action: &str) -> Result<Value, ClientError> {
        let response = self
            .send(
                self.authed(
                    self.http
                        .post(format!("{}/agents/{id}/{action}", self.base)),
                ),
            )
            .await?;
        let status = response.status();
        if !status.is_success() {
            return Err(self.error_from(status, response).await);
        }
        let body = response
            .bytes()
            .await
            .map_err(|e| ClientError::Transport(format!("read response: {e}")))?;
        if body.is_empty() {
            Ok(Value::Null)
        } else {
            serde_json::from_slice(&body)
                .map_err(|e| ClientError::Transport(format!("decode response: {e}")))
        }
    }

    /// `GET /agents/{id}/checkpoints`
    pub async fn list_checkpoints(&self, id: &str) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(
                self.authed(
                    self.http
                        .get(format!("{}/agents/{id}/checkpoints", self.base)),
                ),
            )
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode checkpoints: {e}")))
    }

    /// `GET /agents/{id}/events?after=&limit=`
    pub async fn agent_events(
        &self,
        id: &str,
        after: i64,
        limit: usize,
    ) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(self.authed(self.http.get(format!(
                "{}/agents/{id}/events?after={after}&limit={limit}",
                self.base
            ))))
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode events: {e}")))
    }

    /// `GET /tools`
    pub async fn tools(&self) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(self.authed(self.http.get(format!("{}/tools", self.base))))
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode tools: {e}")))
    }

    /// `GET /models`
    pub async fn models(&self) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(self.authed(self.http.get(format!("{}/models", self.base))))
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode models: {e}")))
    }

    /// `GET /permissions/pending`
    pub async fn pending_permissions(&self) -> Result<Vec<Value>, ClientError> {
        let value = self
            .json_response(self.authed(self.http.get(format!("{}/permissions/pending", self.base))))
            .await?;
        serde_json::from_value(value)
            .map_err(|e| ClientError::Transport(format!("decode permission requests: {e}")))
    }

    /// `POST /permissions/{id}/grant|deny`
    pub async fn decide_permission(&self, id: &str, grant: bool) -> Result<Value, ClientError> {
        let action = if grant { "grant" } else { "deny" };
        self.json_response(
            self.authed(
                self.http
                    .post(format!("{}/permissions/{id}/{action}", self.base)),
            ),
        )
        .await
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /// Resolve `<name|id>` to an agent id. An exact id match wins; otherwise
    /// the name must match exactly one agent (`kern ps` lists names).
    pub async fn resolve_agent(&self, name_or_id: &str) -> Result<String, ClientError> {
        let agents = self.list_agents().await?;
        if agents.iter().any(|a| a["id"].as_str() == Some(name_or_id)) {
            return Ok(name_or_id.to_string());
        }
        let matches: Vec<&Value> = agents
            .iter()
            .filter(|a| a["name"].as_str() == Some(name_or_id))
            .collect();
        match matches.len() {
            0 => Err(ClientError::Api {
                status: StatusCode::NOT_FOUND,
                code: "AGENT_NOT_FOUND".into(),
                message: format!("no agent named or with id {name_or_id:?} (see `kern ps`)"),
                detail: None,
            }),
            1 => Ok(matches[0]["id"].as_str().unwrap_or_default().to_string()),
            _ => Err(ClientError::Transport(format!(
                "ambiguous agent name {name_or_id:?}: {} agents match; use an id (`kern ps`)",
                matches.len()
            ))),
        }
    }
}

/// Resolve the API token exactly like the daemon (SPEC.md §17):
/// `KERN_TOKEN` wins, else `$KERN_HOME/token`.
fn load_token(home: &Path) -> Option<String> {
    if let Ok(token) = std::env::var("KERN_TOKEN") {
        let token = token.trim().to_string();
        if !token.is_empty() {
            return Some(token);
        }
    }
    std::fs::read_to_string(home.join("token"))
        .ok()
        .map(|contents| contents.trim().to_string())
        .filter(|token| !token.is_empty())
}

/// `$KERN_HOME` or `~/.kern` (SPEC.md §17).
pub fn default_home() -> std::path::PathBuf {
    std::env::var_os("KERN_HOME")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| {
            std::env::var_os("HOME")
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|| std::path::PathBuf::from("."))
                .join(".kern")
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `Unreachable` carries the full base URL (scheme included); the Display
    /// must render it once, never `http://http://…` (regression for the
    /// doubled-scheme doctor output).
    #[test]
    fn unreachable_display_renders_a_single_scheme() {
        let err = ClientError::Unreachable("http://127.0.0.1:8787".to_string());
        let text = err.to_string();
        assert!(
            text.contains("http://127.0.0.1:8787"),
            "full URL must appear: {text}"
        );
        assert!(
            !text.contains("http://http://"),
            "scheme must not be doubled: {text}"
        );
    }
}
